language: php

php:
  - 5.3
  - 5.4

before_script:
    - composer install --dev --verbose

script:
    - ./vendor/bin/phpunit --coverage-text --colors --verbose tests/
    - ./vendor/bin/phpcs --encoding=utf-8 --extensions=php --standard=./tests/phpcs.xml -nspv ./
