language: php

php:
  - 5.4

before_script:
    - composer install --dev --verbose

script:
    - ./vendor/bin/phpunit -c phpunit.xml --coverage-text tests/
    - ./vendor/bin/phpcs --encoding=utf-8 --extensions=php --standard=./phpcs.xml -nsp ./
